# Generated by Django 2.1 on 2018-08-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='organization',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
